import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'syllabus',
    'course-structure',
    'technology-stack',
    {
      type: 'category',
      label: 'Week 01 — Development Environment & Tooling',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'week-1/index' },
      items: [
        'week-1/vscode',
        'week-1/uv',
        'week-1/bash-scripting',
        'week-1/git-github',
        'week-1/sqlite',
        'week-1/http-clients',
        'week-1/requestly',
        'week-1/data-formats',
        'week-1/github-pages',
        'week-1/latex',
      ],
    },
    {
      type: 'category',
      label: 'Week 02 — Deployment & API Engineering',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-2/index' },
      items: [
        'week-2/fastapi',
        'week-2/cors-middleware',
        'week-2/google-oauth',
        'week-2/fastapi-advanced',
        'week-2/config-management',
        'week-2/docker-compose',
        'week-2/deployment-platforms',
        'week-2/logging-testing',
        'week-2/observability',
        'week-2/cloudflare-tunnels',
        'week-2/local-llms',
        'week-2/redis-caching',
      ],
    },
    {
      type: 'category',
      label: 'Week 03 — LLM Engineering',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-3/index' },
      items: [
        'week-3/prompt-engineering',
        'week-3/context-engineering',
        'week-3/llm-cli-tools',
        'week-3/ai-coding-assistants',
        'week-3/structured-output',
        'week-3/multimodal-inputs',
        'week-3/vector-embeddings',
        'week-3/similarity-search',
        'week-3/prompt-caching',
        'week-3/langsmith-litellm',
        'week-3/llm-architecture-survey',
      ],
    },
    {
      type: 'category',
      label: 'Week 04 — RAG & Hybrid RAG',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-4/index' },
      items: [
        'week-4/chunking-strategies',
        'week-4/vector-databases',
        'week-4/hybrid-search',
        'week-4/query-augmentation',
        'week-4/reranking',
        'week-4/ragas-evaluation',
        'week-4/multimodal-embeddings',
        'week-4/llm-grounding',
        'week-4/late-chunking',
        'week-4/graphrag',
        'week-4/contextual-retrieval',
        'week-4/semantic-caching',
      ],
    },
    {
      type: 'category',
      label: 'Week 05 — Agentic AI',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-5/index' },
      items: [
        'week-5/agent-fundamentals',
        'week-5/tool-calling',
        'week-5/async-parallelism',
        'week-5/langgraph',
        'week-5/mcp',
        'week-5/custom-mcp-servers',
        'week-5/specialized-agents',
        'week-5/multi-agent-systems',
        'week-5/agent-memory-systems',
        'week-5/lxd-sandboxing',
        'week-5/agent-evaluation',
      ],
    },
    {
      type: 'category',
      label: 'Week 06 — Web Scraping & Data Processing',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-6/index' },
      items: [
        'week-6/playwright-selenium',
        'week-6/crawl4ai',
        'week-6/firecrawl-apify',
        'week-6/scrapy',
        'week-6/anti-bot-patterns',
        'week-6/scheduled-scraping',
        'week-6/document-parsing',
        'week-6/duckdb-parquet',
        'week-6/firestore',
        'week-6/vision-models-for-scraping',
        'week-6/image-processing-pipeline',
        'week-6/speech-ai',
        'week-6/video-understanding',
        'week-6/llm-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Week 07 — CI/CD, Security & Cloud Infrastructure',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-7/index' },
      items: [
        'week-7/github-actions-advanced',
        'week-7/advanced-docker',
        'week-7/llm-security-offensive',
        'week-7/llm-safety-defensive',
        'week-7/owasp-llm-top-10',
        'week-7/vms-ssh',
        'week-7/serverless-functions',
        'week-7/terraform-iac',
        'week-7/cost-alerting',
        'week-7/pubsub-event-driven',
      ],
    },
    {
      type: 'category',
      label: 'Week 08 — MLOps, Fine-Tuning & Model Publishing',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-8/index' },
      items: [
        'week-8/cloud-storage-ml',
        'week-8/bigquery-ml',
        'week-8/mlflow',
        'week-8/finetuning-strategy',
        'week-8/huggingface-ecosystem',
        'week-8/finetuning-techniques',
        'week-8/quantization',
        'week-8/gemma4-finetuning',
        'week-8/gcp-ml-pipeline',
        'week-8/model-publishing',
      ],
    },
    {
      type: 'category',
      label: 'Hands-on Labs',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'labs/index' },
      items: [
        'labs/capstone-projects',
        'labs/all-lab-assignments',
        {
          type: 'category',
          label: 'Week 01',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'labs/week-1/index' },
          items: [
            'labs/week-1/publish-python-library-pypi-uv',
            'labs/week-1/uv-cli-tool-latex-docs',
            'labs/week-1/bash-daily-project-summary',
          ],
        },
        {
          type: 'category',
          label: 'Week 02',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'labs/week-2/index' },
          items: [
            'labs/week-2/gemma-api-hf-spaces-google-auth',
            'labs/week-2/fastapi-observability-grafana',
          ],
        },
        {
          type: 'category',
          label: 'Week 03',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'labs/week-3/index' },
          items: [
            'labs/week-3/youtube-subtitles-topics-json-pipeline',
            'labs/week-3/cost-tracking-dashboard-langsmith',
          ],
        },
        {
          type: 'category',
          label: 'Week 04',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'labs/week-4/index' },
          items: [
            'labs/week-4/capstone-bs-degree-chatbot',
            'labs/week-4/capstone-policy-chatbot',
            'labs/week-4/ragas-evaluation-dashboard',
          ],
        },
        {
          type: 'category',
          label: 'Week 05',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'labs/week-5/index' },
          items: [
            'labs/week-5/capstone-autonomous-research-agent',
            'labs/week-5/capstone-vivaagent-oral-examiner',
            'labs/week-5/context-based-extraction-tool',
          ],
        },
        {
          type: 'category',
          label: 'Week 06',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'labs/week-6/index' },
          items: [
            'labs/week-6/capstone-job-posting-scraper-tracker',
            'labs/week-6/capstone-ai-signature-detection-cropper',
            'labs/week-6/capstone-live-multilingual-travel-translator',
            'labs/week-6/scheduled-scraper-github-actions-cron',
          ],
        },
        {
          type: 'category',
          label: 'Week 07',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'labs/week-7/index' },
          items: [
            'labs/week-7/red-team-your-api-guardrails',
            'labs/week-7/full-cicd-cloud-run',
          ],
        },
        {
          type: 'category',
          label: 'Week 08',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'labs/week-8/index' },
          items: [
            'labs/week-8/capstone-production-finetuned-model-mlops',
            'labs/week-8/full-gcp-pipeline-bqml-vertex-cloud-run',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Projects',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'projects/index' },
      items: ['projects/project-1', 'projects/project-2', 'projects/project-3'],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'reference/index' },
      items: ['reference/tools-glossary', 'reference/command-cheatsheet'],
    },
  ],
};

export default sidebars;
