import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Week 1 — Dev Environment & Version Control',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'week-1/index' },
      items: [
        'week-1/vscode-setup',
        'week-1/uv-python',
        'week-1/bash-scripting',
        'week-1/git-github',
        'week-1/sqlite',
        'week-1/github-pages',
      ],
    },
    {
      type: 'category',
      label: 'Week 2 — Containers, APIs & Deployment',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-2/index' },
      items: [
        'week-2/fastapi',
        'week-2/docker',
        'week-2/vercel-render',
        'week-2/huggingface',
        'week-2/cors-rest',
        'week-2/google-auth',
      ],
    },
    {
      type: 'category',
      label: 'Week 3 — Prompt Engineering & LLM Fundamentals',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-3/index' },
      items: [
        'week-3/prompt-engineering',
        'week-3/structured-output',
        'week-3/llm-extraction',
        'week-3/function-calling',
        'week-3/llm-cli',
        'week-3/embeddings',
        'week-3/prompt-caching',
        'week-3/instructor',
      ],
    },
    {
      type: 'category',
      label: 'Week 4 — RAG, Vector DBs & Hybrid Search',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-4/index' },
      items: [
        'week-4/chunking-strategies',
        'week-4/vector-databases',
        'week-4/hybrid-search',
        'week-4/reranking',
        'week-4/rag-evaluation',
        'week-4/multimodal-embeddings',
        'week-4/contextual-retrieval',
        'week-4/graphrag',
      ],
    },
    {
      type: 'category',
      label: 'Week 5 — Agentic AI & MCP',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-5/index' },
      items: [
        'week-5/llm-agents',
        'week-5/pydantic-ai',
        'week-5/mcp-protocol',
        'week-5/mcp-server',
        'week-5/multimodal-agents',
        'week-5/langgraph',
      ],
    },
    {
      type: 'category',
      label: 'Week 6 — Media Processing & Vision',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-6/index' },
      items: [
        'week-6/vision-models',
        'week-6/image-processing',
        'week-6/grounding-dino',
        'week-6/audio-processing',
        'week-6/image-generation',
        'week-6/grounding-dino-tiny',
        'week-6/colpali',
        'week-6/polars',
        'week-6/duckdb-parquet',
      ],
    },
    {
      type: 'category',
      label: 'Week 7 — Finetuning & Publishing',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-7/index' },
      items: [
        'week-7/finetuning-strategy',
        'week-7/gemma-finetuning',
        'week-7/huggingface-ecosystem',
        'week-7/python-packaging',
        'week-7/pypi-publishing',
        'week-7/dpo-finetuning',
        'week-7/uv-tools-uvx',
      ],
    },
    {
      type: 'category',
      label: 'Week 8 — CI/CD & Security',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-8/index' },
      items: [
        'week-8/github-actions',
        'week-8/advanced-docker',
        'week-8/llm-security',
        'week-8/nemo-guardrails',
        'week-8/security-best-practices',
        'week-8/openclaw-red-teaming',
      ],
    },
    {
      type: 'category',
      label: 'Bonus Week 9 — MLOps on GCP (Part 1)',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-9/index' },
      items: [
        'week-9/mlflow',
        'week-9/vertex-ai',
        'week-9/gcp-pipelines',
        'week-9/bigquery-ml',
        'week-9/data-versioning',
      ],
    },
    {
      type: 'category',
      label: 'Bonus Week 10 — MLOps on GCP (Part 2)',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'week-10/index' },
      items: [
        'week-10/cloud-run-ml',
        'week-10/model-monitoring',
        'week-10/pubsub-functions',
        'week-10/artifact-registry',
        'week-10/cost-optimization',
      ],
    },
    {
      type: 'category',
      label: 'Labs',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'labs/index' },
      items: [
        'labs/lab-01-chatbot',
        'labs/lab-02-rag-chatbot',
        'labs/lab-03-finetuning',
        'labs/lab-04-hybrid-rag',
        'labs/lab-05-signature-detection',
        'labs/lab-06-ai-agent-mcp',
        'labs/lab-07-cicd',
        'labs/lab-08-mlops-gcp',
        'labs/lab-09-llm-red-teaming',
        'labs/lab-10-instructor-extraction',
        'labs/lab-11-prompt-caching',
        'labs/lab-12-contextual-retrieval',
        'labs/lab-13-graphrag',
        'labs/lab-14-langgraph',
        'labs/lab-15-polars-duckdb',
        'labs/lab-16-guardrails-redteam',
        'labs/lab-17-system-design-review',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: true,
      items: [
        'reference/tools-glossary',
        'reference/command-cheatsheet',
      ],
    },
  ],
};

export default sidebars;
